# Generated by Django 3.0.4 on 2020-05-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy_food', '0004_auto_20200413_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Doctor'), (2, 'Nurse'), (3, 'Surgen')], null=True),
        ),
    ]
