# Generated by Django 3.0.4 on 2020-05-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy_food', '0008_auto_20200516_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='dflt_img.jpg', null=True, upload_to=''),
        ),
    ]
